[build]
  command = "npm run build;cd functions"
  publish = "build/"
  functions = "functions/"
[[plugins]]
    package = "./plugins/pnpm-preinstaller"
[build.environment]
    NPM_FLAGS="--prefix=./tmp"