[build]
  command = "npm run build"
  publish = "build/"
  functions = "functions/"
[[plugins]]
   package = "@netlify/plugin-functions-install-core"
[[plugins]]
    package = "./plugins/pnpm-preinstaller"
[build.environment]
    NPM_FLAGS="--prefix=./tmp"