query Resources {
    airports(first: 500) {
        edges {
            node {
                uri
            }
        }
    }
    
    fleet(first: 500) {
        edges {
            node {
                uri
            }
        }
    }
    
    subfleets(first: 500) {
        edges {
            node {
                uri
            }
        }
    }
    
    properties(first: 500) {
        edges {
            node {
                uri
            }
        }
    }
    
    posts(first: 500) {
        edges {
            node {
                uri
            }
        }
    }

    categories(first: 500) {
        edges {
            node {
                uri
            }
        }
    }

    tags(first: 1000) {
        edges {
            node {
                uri
            }
        }
    }

    classes(first: 500) {
        edges {
            node {
                uri
            }
        }
    }

    pages(first: 500) {
        edges {
            node {
                uri
            }
        }
    }
}